### ISSUE TITLE
Dynamic editor height

### ISSUE THREAD

**Issue by thienanle** [zenoamaro/react-quill#118]
Is there a way to change the editor height to shrink/expand to fit its contents?

**Comment by alexkrolick** [comment]
It will expand, set it to a smaller initial height

**Comment by alagos** [comment]
Not sure if is the same problem, but to whoever has a similar problem, I wrote this style to set min/max heights to the editor and activate horizontal/vertical scrolling:
```css
.ql-editor{
  min-height: 100px !important;
  max-height: 300px;
  overflow: hidden;
  overflow-y: scroll;
  overflow-x: scroll;
}
```
