### ISSUE TITLE
Allow focus on editor to happen anywhere within an empty editor

### ISSUE THREAD

**Issue by aliciawood** [zenoamaro/react-quill#205]
If you look at the codepen below and try to click in the bottom left corner of the editor to focus the editor.
Expected: editor will gain focus and cursor will show
Actual: editor does not focus

If empty editor is focused (with cursor shown) and click in the bottom left corner.
Expected: editor will stayed focused
Actual: editor loses focus and cursor disappears

https://codepen.io/alexkrolick/pen/xgyOXQ?editors=0010#0

Quill version: 
- [X ] 1.0.0-rc-2

**Comment by alexkrolick** [comment]
Good catch, the CSS in the demo should really have the min-height on the editor div instead of the container.

Change this:

```css
.app .ql-container {
  min-height: 10rem;
  border-bottom-left-radius: 0.5em;
  border-bottom-right-radius: 0.5em;
  background: #fefcfc;
}

```

to this:

```css
.app .ql-container {
  border-bottom-left-radius: 0.5em;
  border-bottom-right-radius: 0.5em;
  background: #fefcfc;
}

.app .ql-editor {
  min-height: 10rem;
}
```
