### ISSUE TITLE
How to set max-width to img in editor

### ISSUE THREAD

**Issue by havantuan** [zenoamaro/react-quill#295]
Hello. I want to insert img and set max-width to img in editor.
Please help me.

**Comment by alexkrolick** [comment]
You can use CSS to target the `img` tag and any classes added by Quill inside the `.ql-editor` class:

```css
.ql-editor img {
  max-width: 250px;
}
```
