### ISSUE TITLE
Can react-quill set the row spacing and word spacing?

### ISSUE THREAD

**Issue by tyawei** [zenoamaro/react-quill#506]
I need to set some spacing between lines and words, while I found no configuration item in the Modules that can solve it. My question is whether react-quill supports my need? Or is there any plan to add the function？

**Comment by alexkrolick** [comment]
Is this something you can do with CSS?

```css
.ql-editor p { margin-top: 10px; letter-spacing: 2px; }
```
